version: '3.7'
services:
  prometheus:
    image: prom/prometheus:v2.7.2
    restart: unless-stopped
    command: [ "--config.file=/etc/prometheus/prometheus.yml",
             "--storage.tsdb.path=/prometheus",
             "--web.console.libraries=/usr/share/prometheus/console_libraries",
             "--web.console.templates=/usr/share/prometheus/consoles",
             "--storage.tsdb.retention.time=96h" ]
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  node-exporter:
    image: prom/node-exporter:v0.17.0
    restart: unless-stopped
  grafana:
    image: grafana/grafana:6.0.1
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SECURITY_SECRET_KEY=123214dad

      - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/node-exporter.json:/var/lib/grafana/dashboards/node-exporter.json

networks:
  default:
    name: nginx
