version: '3.7'
services:
  prometheus:
    image: prom/prometheus:v2.5.0
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
    ports:
      - 9090:9090
  prom-node-export:
    image: prom/node-exporter:v0.16.0
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9100:9100
  # grafana:
  #   image: grafana/grafana:5.3.4
  #   restart: unless-stopped
  #   volumes:
  #     - ./grafana.ini:/etc/prometheus/grafana.ini
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - prometheus