global:
  scrape_interval:     15s
  external_labels:
    monitor: 'self-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['prom-node-export:9100']
        labels:
          group: 'production'